### ISSUE TITLE
Split core logic and runner into different subprojects

### ISSUE THREAD

**Issue by petertrr** [analysis-dev/serialization-adapters#8]
Now it's sort of circular dependency: Adapter implementation depends on adapter-core, but adapter-core is used to run implementation too

**Comment by orchestr7** [comment]
Also right now we have `KxSerializationAdapter` that works only with Input/OutputStreamReader. 
Need also to support more convenient types for input and output, like the simple List<String>. Same about the read from and to the file (okio)?

**Comment by orchestr7** [comment]
May be it will be also great to see this part as a MPP subproject
